inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-rails
  - rubocop-performance

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
