SECRET: 'SecretToken'

DEFAULT_LOCALE: 'it'
TIME_ZONE: 'Rome'

HOST: 'www.interconn.it'

MAIL_SENDER: 'InterConn <info@interconn.it>'

TICKETS_EMAIL: 'help@interconn.it'
INQUIRIES_EMAIL: 'help@interconn.it'

SMTP_ADDRESS: 'mail.interconn.it'
SMTP_PORT: '25'
SMTP_DOMAIN: 'interconn.it'
SMTP_USERNAME: 'devel@interconn.it'
SMTP_PASSWORD: 'TestPassword'
SMTP_AUTH: 'plain'
SMTP_STARTTLS: 'true'
SMTP_OPENSSL_VERIFY: 'none'

FACEBOOK_URL: 'https://www.facebook.com/interconn.isp'
TWITTER_URL: 'https://twitter.com/InterConnISP'
# GOOGLE_PLUS_URL: 'https://plus.google.com/b/YourPageID'
GITHUB_URL: 'https://github.com/interconn-isp'
# SKYPE_URL: 'skype:interconn.wisp?chat'

CAREERS_URL: 'https://www.hellohired.com/interconn'

SITE_NAME: 'InterConn'

# STATUS_URL: 'http://status.interconn.it'
BLOG_URL: 'https://medium.com/@interconn'
# CP_URL: 'http://customers.interconn.it'

GA_ID: 'UA-54085084-1'

IUBENDA_POLICY_ID: '131846'

NEWRELIC_LICENSE_KEY: 'YourNewRelicLicenseKey'
